name: Dependency jobs
run-name: Nombre de la ejecucion del Dependency jobs

on:
  workflow_dispatch:

concurrency:
  group: grupo1
  cancel-in-progress: true
  
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: step11
        run: exit 1
        continue-on-error: true
      - name: step2
        run: |
          echo "var1=valor1" >> "$GITHUB_ENV"
          echo ${{ job.status }}
          echo ${{ steps.step11.outcome }}
          echo ${{ steps.step11.conclusion }}
      - name: step3
        env: 
          var2: valor2
        run: |
          echo "${{ env.var1 }}"
          echo "${{ toJSON(env) }}"
  job2:
    name: job2
    needs: [job1]
    if: always()
    continue-on-error: true
    runs-on: ubuntu-latest        
    steps:
      - name: step1
        run: exit 1
  job3:
    name: job3
    needs: [job2]
    runs-on: ubuntu-latest        
    steps:
      - name: step1
        run: | 
          echo "${{ toJSON(needs) }}"
  job4:
    name: job4
    needs: [job3]
    runs-on: ubuntu-latest        
    steps:
      - name: step1
        run: echo "job4"
  job5:
    name: job5
    needs: [job4]
    if: failure()
    runs-on: ubuntu-latest        
    steps:
      - name: step1
        run: echo "job5"
  job6:
    name: job6
    needs: [job5]
    runs-on: ubuntu-latest        
    steps:
      - name: step1
        run: echo "job6"
  job7:
    name: job7
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: sleep 20
  job8:
    name: job8
    runs-on: ubuntu-latest
    if: cancelled()
    needs: [job7]
    steps:
      - name: step1
        run: sleep 1
        
