name: Workflow de prueba2
run-name: Nombre de la ejecucion del workflow de prueba2

on:
  workflow_dispatch:

jobs:
  job1:
    name: Nombre job 1
    runs-on: ubuntu-latest        
    steps:
      - name: Nombre step 1
        id: step11
        uses: actions/checkout@v4
      - name: Nombre step 2
        id: step12
        working-directory: directorio
        run: pwd; ls -la; echo $GITHUB_WORKSPACE 
