name: Workflow de prueba
run-name: Nombre de la ejecucion del workflow de prueba

on:
  workflow_dispatch:

jobs:
  job1:
    name: Nonbre job 1
    runs-on: ubuntu-latest
    steps:
      - name: Nombre step 1
        id: step11
        env:
          ENV1: prueba1
          ENV2: prueba2
        run: pwd; ls -la; echo $ENV1; echo $GITHUB_WORKSPACE      
      - name: Nombre step 2
        id: step12
        uses: actions/checkout@v4
      - name: Nombre step 3
        id: step13
        run: pwd; ls -la; mkdir -p upload/dir/dir1; mkdir upload/dir/dir2; ls -la; touch upload/dir/dir1/file1; touch upload/dir/dir2/file2
      - name: Nombre step 4
        id: step14
        uses: actions/upload-artifact@v4
        with:
          name: artifact-fer
          path: upload/dir/
  job2:
    name: Nombre job 2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Nombre step 1
        id: step21
        uses: actions/download-artifact@v4
        with:
          name: artifact-fer
          path: me/lo/invento
      - name: Nombre step 2
        id: step22
        run: pwd; ls -la; ls -la /me/lo/invento
  
  
