name: Workflow de prueba2
run-name: Nombre de la ejecucion del workflow de prueba2

on:
  workflow_dispatch:

jobs:
  job1:
    name: Nonbre job 1
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: directorio
    steps:
      - name: Nombre step 1
        id: step11
        env:
          ENV1: prueba1
          ENV2: prueba2
        run: pwd; ls -la; echo $ENV1; echo $GITHUB_WORKSPACE   
