# This is a basic workflow to help you get started with Actions

name: SKIP

on:
  workflow_dispatch:

jobs:
  success1:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  skip:
    runs-on: ubuntu-latest
    needs: [success1]
    if: 1 == 3
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  success2:
    runs-on: ubuntu-latest
    needs: [skip]
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      


