# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: 1 == 3
    steps:
      - name: Run a one-line script
        run: echo Hello, world!


