# This is a basic workflow to help you get started with Actions

name: SKIP

on:
  workflow_dispatch:

jobs:
  skip:
    runs-on: ubuntu-latest
    if: 1 == 3
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  success:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        if: 3 == 1
        run: echo Hello, world!
      - name: Run a one-line script
        if: always ()
        run: echo "${{ job.status }}"
      - name: Run a one-line script
        run: echo "${{ job.status }}"
      


